### ISSUE TITLE
Demo login credentials not valid

### ISSUE THREAD

**Issue by alucic** [kJamesy/Nifty-Newsletter#1]
Hi there, I would like to see demo page but trying to log in with given credentials return "User not found"

![screen shot 2014-09-11 at 10 55 25](https://cloud.githubusercontent.com/assets/1689028/4231463/6fae6b98-3991-11e4-9fe3-dc3839e94a70.png)

Am I doing something wrong?

Thanks

**Comment by kJamesy** [comment]
Yes you are. My bad though. The email address should be demo@email-newsletter.info :)

**Comment by alucic** [comment]
that was fast! :+1:
